package net;

public interface DhcpProperties {
    int DHCP_MSGTYPE_LEN = 1;
    int DHCP_HRDTYPE_LEN = 1;
    int DHCP_HRDLEN_LEN = 1;
    int DHCP_HOPS_LEN = 1;
    int DHCP_TRANSID_LEN = 4;
    int DHCP_SECELAP_LEN = 2;
    int DHCP_BPFLAGS_LEN = 2;
    int DHCP_CLIENTIP_LEN = IpAddress.WIDTH;
    int DHCP_OWNERIP_LEN = IpAddress.WIDTH;
    int DHCP_NSERVIP_LEN = IpAddress.WIDTH;
    int DHCP_NRELAIP_LEN = IpAddress.WIDTH;
    int DHCP_CLIENTMAC_LEN = MacAddress.WIDTH;
    int DHCP_SERVERHOSTNAME_LEN = 64;
    int DHCP_BOOTFILENAME_LEN = 128;

    int DHCP_MSGTYPE_POS = 0;
    int DHCP_HRDTYPE_POS = DHCP_MSGTYPE_POS + DHCP_MSGTYPE_LEN;
    int DHCP_HRDLEN_POS = DHCP_HRDTYPE_POS + DHCP_HRDTYPE_LEN;
    int DHCP_HOPS_POS = DHCP_HRDLEN_POS + DHCP_HRDLEN_LEN;
    int DHCP_TRANSID_POS = DHCP_HOPS_POS + DHCP_HOPS_LEN;
    int DHCP_SECELAP_POS = DHCP_TRANSID_POS + DHCP_TRANSID_LEN;
    int DHCP_BPFLAGS_POS = DHCP_SECELAP_POS + DHCP_SECELAP_LEN;
    int DHCP_CLIENTIP_POS = DHCP_BPFLAGS_POS + DHCP_BPFLAGS_LEN;
    int DHCP_OWNERIP_POS = DHCP_CLIENTIP_POS + DHCP_CLIENTIP_LEN;
    int DHCP_NSERVIP_POS = DHCP_OWNERIP_POS + DHCP_OWNERIP_LEN;
    int DHCP_NRELAIP_POS = DHCP_NSERVIP_POS + DHCP_NSERVIP_LEN;
    int DHCP_CLIENTMAC_POS = DHCP_NRELAIP_POS + DHCP_NRELAIP_LEN;
    int DHCP_SERVERHOSTNAME_POS = DHCP_CLIENTMAC_POS + DHCP_CLIENTMAC_LEN + 10;
    int DHCP_BOOTFILENAME_POS = DHCP_SERVERHOSTNAME_POS + DHCP_SERVERHOSTNAME_LEN;

    int DHCP_HEADER_LEN = DHCP_BOOTFILENAME_POS + DHCP_BOOTFILENAME_LEN;
}
