package net;

public interface DnsProperties {
    int DNS_TRANSID_LEN = 2;
    int DNS_FLAGS_LEN = 2;
    int DNS_QUESTIONS_LEN = 2;
    int DNS_ANSWERRR_LEN = 2;
    int DNS_AUTHORITYRR_LEN = 2;
    int DNS_ADDITRR_LEN = 2;

    int DNS_TRANSID_POS  = 0;
    int DNS_FLAGS_POS = DNS_TRANSID_POS + DNS_TRANSID_LEN;
    int DNS_QUESTIONS_POS = DNS_FLAGS_POS + DNS_FLAGS_LEN;
    int DNS_ANSWERRR_POS = DNS_QUESTIONS_POS + DNS_QUESTIONS_LEN;
    int DNS_AUTHORITYRR_POS = DNS_ANSWERRR_POS + DNS_ANSWERRR_LEN;
    int DNS_ADDITRR_POS = DNS_AUTHORITYRR_POS + DNS_AUTHORITYRR_LEN;

    int DNS_HEADER_LEN = DNS_ADDITRR_POS + DNS_ADDITRR_LEN;
}
