package net;

public interface PcapHProperties {
    int PH_TIMESTAMP_LEN = 4;
    int PH_USTIMESTAMP_LEN = 4;
    int PH_TOTALPACKETLENGHT_LEN = 4;
    int PH_PACKETLENGHT_LEN = 4;

    int PH_TIMESTAMP_POS = 0;
    int PH_USTIMESTAMP_POS =  PH_TIMESTAMP_POS + PH_TIMESTAMP_LEN;
    int PH_TOTALPACKETLENGHT_POS = PH_USTIMESTAMP_POS + PH_USTIMESTAMP_LEN;
    int PH_PACKETLENGHT_POS = PH_TOTALPACKETLENGHT_POS + PH_TOTALPACKETLENGHT_LEN;

    int PH_SIZE = PH_PACKETLENGHT_POS + PH_PACKETLENGHT_LEN;
}
